package org.example.factories;

/**
 * Enumeration of all 22 synthetic scene background types, grouped by complexity tier.
 *
 * <p>Backgrounds are generated by {@link BackgroundFactory} at any requested size.
 * The tier classification reflects how much visual noise/complexity is present:
 * <ul>
 *   <li>Tier 1 — Minimal (solid fills, no colour)
 *   <li>Tier 2 — Low (gradients, light noise)
 *   <li>Tier 3 — Medium (structured colour patterns)
 *   <li>Tier 4 — High (rich colour clutter)
 * </ul>
 */
public enum BackgroundId {

    // -------------------------------------------------------------------------
    // Tier 1 — Minimal  (3)
    // -------------------------------------------------------------------------
    BG_SOLID_BLACK,   // Plain black
    BG_SOLID_WHITE,   // Plain white
    BG_SOLID_GREY,    // 50% grey

    // -------------------------------------------------------------------------
    // Tier 2 — Low complexity  (7)
    // -------------------------------------------------------------------------
    BG_GRADIENT_H_GREY,      // Horizontal greyscale gradient (black → white)
    BG_GRADIENT_V_GREY,      // Vertical greyscale gradient (black → white)
    BG_GRADIENT_H_COLOUR,    // Horizontal colour gradient (deep blue → deep red)
    BG_GRADIENT_V_COLOUR,    // Vertical colour gradient (dark green → dark purple)
    BG_GRADIENT_RADIAL_GREY, // Radial gradient — bright centre, dark edges (greyscale)
    BG_GRADIENT_RADIAL_COLOUR, // Radial gradient — warm centre (orange), cool edges (teal)
    BG_NOISE_LIGHT,          // Low-level Gaussian noise (σ=8) on a mid-grey base

    // -------------------------------------------------------------------------
    // Tier 3 — Medium complexity  (6)
    // -------------------------------------------------------------------------
    BG_NOISE_HEAVY,      // Heavy Gaussian noise (σ=35) on a mid-grey base
    BG_GRID_FINE,        // Dense fine grid lines (every 16 px) in dark cyan on black
    BG_GRID_COARSE,      // Coarse grid lines (every 64 px) in dark blue on dark grey
    BG_HATCHING,         // Diagonal hatching at 45° in dark green on dark grey
    BG_RANDOM_LINES,     // 20–40 randomly placed/angled line segments in random colours
    BG_RANDOM_CIRCLES,   // 10–20 randomly placed circle outlines in random colours

    // -------------------------------------------------------------------------
    // Tier 4 — High complexity  (5)
    // -------------------------------------------------------------------------
    BG_RANDOM_MIXED,    // 30–50 random lines, circles, rectangles — each a random colour
    BG_DENSE_TEXT,      // Tiled random alphanumeric chars in random colours on dark bg
    BG_CIRCUIT_LIKE,    // PCB-style orthogonal traces in green/gold on dark brown
    BG_ORGANIC,         // Irregular blobs + curved lines in warm/cool colour bands
    BG_COLOURED_NOISE;  // Full-frame RGB noise (each channel independently randomised)

    // -------------------------------------------------------------------------
    // Metadata helpers
    // -------------------------------------------------------------------------

    /** Returns the complexity tier (1–4) for this background. */
    public int tier() {
        int ord = ordinal();
        if (ord < 3)  return 1;
        if (ord < 10) return 2;
        if (ord < 16) return 3;
        return 4;
    }

    /** Returns a short human-readable complexity label. */
    public String complexityLabel() {
        return switch (tier()) {
            case 1 -> "Minimal";
            case 2 -> "Low";
            case 3 -> "Medium";
            case 4 -> "High";
            default -> "Unknown";
        };
    }
}

